services:
    database:
      image: postgres:10
      environment:
          POSTGRES_DB: "retailer-db"
          POSTGRES_USER: "retailer-user"
          POSTGRES_PASSWORD: "retailer-password"
      restart: always
      ports:
          - "5432:5432"
    keycloak:
      image: quay.io/keycloak/keycloak:26.2.0
      ports:
        - "8082:8080"
      environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      command: start-dev